
controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    propeller_velocity_controller:
      type: velocity_controllers/JointGroupVelocityController
      joints:
        - propeller1_joint
        - propeller2_joint
        - propeller3_joint
        - propeller4_joint
      gains:
        propeller1_joint: {p: 0.1, i: 0.01, d: 0.0}
        propeller2_joint: {p: 0.1, i: 0.01, d: 0.0}
        propeller3_joint: {p: 0.1, i: 0.01, d: 0.0}
        propeller4_joint: {p: 0.1, i: 0.01, d: 0.0}